In [1]:
import pandas as pd

df = pd.read_csv('data/vgsales.csv')

df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [2]:
df["Name"].value_counts()[df["Name"].value_counts() > 1]

Name
Need for Speed: Most Wanted                12
FIFA 14                                     9
Madden NFL 07                               9
LEGO Marvel Super Heroes                    9
Ratatouille                                 9
                                           ..
Grooverider: Slot Car Thunder               2
WSC REAL 09: World Snooker Championship     2
Sakura-Sou no Pet na Kanojo                 2
Heart no Kuni no Alice                      2
Akatsuki no Goei Trinity                    2
Name: count, Length: 2775, dtype: int64

In [3]:
df[df["Name"] == "Need for Speed: Most Wanted"]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
252,253,Need for Speed: Most Wanted,PS2,2005.0,Racing,Electronic Arts,2.03,1.79,0.08,0.47,4.37
498,499,Need for Speed: Most Wanted,PS3,2012.0,Racing,Electronic Arts,0.71,1.51,0.06,0.61,2.89
1173,1175,Need for Speed: Most Wanted,X360,2012.0,Racing,Electronic Arts,0.62,0.80,0.01,0.15,1.58
1530,1532,Need for Speed: Most Wanted,X360,2005.0,Racing,Electronic Arts,1.00,0.17,0.02,0.10,1.29
1742,1744,Need for Speed: Most Wanted,PSV,2012.0,Racing,Electronic Arts,0.38,0.52,0.01,0.25,1.16
2005,2007,Need for Speed: Most Wanted,XB,2005.0,Racing,Electronic Arts,0.53,0.46,0.00,0.05,1.04
3585,3587,Need for Speed: Most Wanted,GC,2005.0,Racing,Electronic Arts,0.43,0.11,0.00,0.02,0.56
5900,5902,Need for Speed: Most Wanted,PC,2005.0,Racing,Electronic Arts,0.02,0.23,0.00,0.05,0.30
6149,6151,Need for Speed: Most Wanted,WiiU,2013.0,Racing,Electronic Arts,0.14,0.12,0.00,0.02,0.28
6278,6280,Need for Speed: Most Wanted,DS,2005.0,Racing,Electronic Arts,0.24,0.01,0.00,0.02,0.27
6492,6494,Need for Speed: Most Wanted,GBA,2005.0,Racing,Electronic Arts,0.19,0.07,0.00,0.00,0.26
11676,11678,Need for Speed: Most Wanted,PC,2012.0,Racing,Electronic Arts,0.00,0.06,0.00,0.02,0.08

In [4]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  str
 2   Platform      16598 non-null  str
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  str
 5   Publisher     16540 non-null  str
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), str(4)
memory usage: 2.1 MB

In [10]:
df_cleaned = pd.read_csv('data/vgsales_cleaned.csv')

In [17]:
df_cleaned.duplicated().sum()

np.int64(0)

In [21]:
def dat_descriptivos(df):
    """obtiene  datos descriptivos por medio de agreagaciones"""
    print("--------------------- DATOS DESCRIPTIVOS -------------------------")
    resumen = df[["Global_Sales", "Other_Sales", "JP_Sales","NA_Sales", "EU_Sales"]].agg(["mean", "median", "sum", "var", "std", "kurt"])
    print(resumen)
    print()

In [19]:
df_cleaned

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16286,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16287,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16288,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16289,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16290,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [22]:
dat_descriptivos(df_cleaned)

--------------------- DATOS DESCRIPTIVOS -------------------------
        Global_Sales  Other_Sales     JP_Sales     NA_Sales     EU_Sales
mean        0.540910     0.048426     0.078833     0.265647     0.147731
median      0.170000     0.010000     0.000000     0.080000     0.020000
sum      8811.970000   788.910000  1284.270000  4327.650000  2406.690000
var         2.456569     0.036131     0.097269     0.676395     0.259389
std         1.567345     0.190083     0.311879     0.822432     0.509303
kurt      596.004589  1011.974945   191.209577   642.909262   746.431300

In [23]:
resumen = df_cleaned[["Global_Sales", "Other_Sales", "JP_Sales","NA_Sales", "EU_Sales"]].agg(["mean", "median", "sum", "var", "std", "kurt"])
resumen

        Global_Sales  Other_Sales     JP_Sales     NA_Sales     EU_Sales
mean        0.540910     0.048426     0.078833     0.265647     0.147731
median      0.170000     0.010000     0.000000     0.080000     0.020000
sum      8811.970000   788.910000  1284.270000  4327.650000  2406.690000
var         2.456569     0.036131     0.097269     0.676395     0.259389
std         1.567345     0.190083     0.311879     0.822432     0.509303
kurt      596.004589  1011.974945   191.209577   642.909262   746.431300